title: Sharing Unity projects
hero_image: images/banner.png
description: How to share projects built with Unity
version: 4
listed: false
copyedit: false
last_tested: "2021-11-16"
steps:
  - title: Sharing Unity projects